Add kubectl plugin functionality for viewing namespace ancestry.
1. If the user has namespace get permission on the entire
hierarchy:

$ kubectl plugin stolos get namespaces --namespace frontend

frontend > eng > acme

2. If the user has permission on frontend and eng, but not
eng's parent

$ kubectl plugin stolos get namespaces --namespace frontend

frontend > eng > ...

3. If the user does not have namespace get permission
on frontend:

$ kubectl plugin stolos get namespaces --namespace frontend

E1120 15:54:20.029050   64838 kubectl-stolos.go:39] Failed to invoke
command "get namespaces": namespaces "frontend" is forbidden: User
"alice@google.com" cannot get namespaces in the namespace "frontend"
error: exit status 1

4. If the user has namespace get permission on the root namespace
(acme):

$ kubectl plugin stolos get namespaces --namespace acme

acme

BUG=69069056

Change-Id: Id1425cfe2aa40ed02de0625ada3bdd61853f8065