Revert "Run `dep check` in CI targets."
This reverts commit a90ab8f7138f3a878d33922d864c813a810e60d3.

Tests fail on prow with this error:
Error: No such image: gcr.io/nomos-public/buildenv:v0.1.4
Unable to find image 'gcr.io/nomos-public/buildenv:v0.1.4' locally
docker: Error response from daemon: manifest for gcr.io/nomos-public/buildenv:v0.1.4 not found.

Change-Id: I2194f1f34aba77a41a591642d4385bde35037b04